package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
)

const (
	WIKI_URL      = "https://wiki.bambulab.com/en/hms/home"
	JSON_URL      = "https://e.bambulab.com/wikijs/GetHmsWikiList.php"
	MAX_ENTRIES   = 1_000
	MAX_PAGES     = 10
	_PACKAGE_NAME = "hms"
)

// HMSResp represents the Health Management System records returned
// by the REST API [JSON_URL] that's used to populate hms entries in the wiki [WIKI_URL].
type HMSResp struct {
	Result int `json:"result"`
	T      int `json:"t"`
	Ver    int `json:"ver"`
	Data   struct {
		DeviceId   int    `json:"deviceid"`
		DeviceCode string `json:"devicecode"`
		Hms        string `json:"hms"`
		Lang       string `json:"lang"`
		Page       int    `json:"page"`
		Size       int    `json:"size"`
		Total      int    `json:"total"`
	} `json:"data"`
}

// TODO:
// - finish response struct
// - logic that keeps pulling until "all" records are pulled (or [MAX_PAGES] reached)
// - use of "hms_fallback.json" which contains all records

const _template = `// Code generated by hms.go; DO NOT EDIT.
package {{ PACKAGE_NAME }}

var HmsErrors = map[string]string{
	{{ range .}}
	"{{ .Ecode }}": "{{ .Info }}",
	{{ end }}
}
`

func main() {
	// specify path of output file

	//	exe, _ := os.Executable()
	//	root := filepath.Dir(filepath.Dir(exe))
	//	outfile := root + "internal/hms/errors.go"

	// query API endpoint for hms error spec
	resp, err := http.Get(fmt.Sprintf("%s?size=%d", JSON_URL, MAX_ENTRIES))
	if err != nil {
		// TODO: use fallback json file
		fmt.Println(err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		// TODO: use fallback json file
		fmt.Println(err)
		os.Exit(1)
	}

	os.WriteFile("./hms_fallback.json", data, 0o644)

	fmt.Println(string(data))

	// populate template
}
